#!/bin/bash
### BEGIN INIT INFO
# Provides:          reseed
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       an I2P reseed server
### END INIT INFO

SCRIPT='/usr/bin/reseed-tools'
RUNAS=i2psvc
NETDBDIR=/var/lib/i2p/i2p-config/netDb
RUNDIR=/var/lib/i2p/i2p-config/reseed
MORE_OPTIONS=""
PIDFILE="$RUNDIR/reseed.pid"
TIMEOUT=60
if [ -f /etc/default/reseed ]; then
    . /etc/default/reseed
fi
RUNOPTS=" reseed --yes=true --netdb=$NETDBDIR $MORE_OPTIONS "

start() {
    if [ ! -d "$RUNDIR" ]; then
        mkdir -p "$RUNDIR"
        chown $RUNAS:$RUNAS "$RUNDIR"
    fi
    if [ -z "$RESEED_EMAIL" ]; then
        echo "Error: RESEED_EMAIL not configured" >&2
        return 1
    fi
    start-stop-daemon --background \
        --user $RUNAS \
        --chuid $RUNAS \
        --exec $SCRIPT \
        --chdir $RUNDIR \
        --make-pidfile \
        --pidfile $PIDFILE \
        --start \
        --startas $SCRIPT -- $RUNOPTS

    for i in $(seq 1 $TIMEOUT); do
        if status >/dev/null; then
            return 0
        fi
        sleep 1
    done
    return 1
}

stop() {
    start-stop-daemon \
      --user $RUNAS \
      --exec $SCRIPT \
      --chdir $RUNDIR \
      --remove-pidfile \
      --pidfile $RUNDIR/reseed.pid \
      --stop
}

status() {
    start-stop-daemon \
      --user $RUNAS \
      --exec $SCRIPT \
      --chdir $RUNDIR \
      --pidfile $RUNDIR/reseed.pid \
      --status
}

restart() {
    stop
    start
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not removed" >&2
    update-rc.d -f reseed remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall|status}"
esac
